// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJVha9vajLAvHf9fiO23vYlfSyCVYugV4',
    appId: '1:142912054370:web:f7c1b005e4b5dc55d75d3b',
    messagingSenderId: '142912054370',
    projectId: 'tickit-2bb0e',
    authDomain: 'tickit-2bb0e.firebaseapp.com',
    storageBucket: 'tickit-2bb0e.firebasestorage.app',
    measurementId: 'G-2XTB84L3JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiQ3Ancv-gamTsyU1dyPdvPSSEUiZE-UI',
    appId: '1:142912054370:android:c97a29a6a75239f9d75d3b',
    messagingSenderId: '142912054370',
    projectId: 'tickit-2bb0e',
    storageBucket: 'tickit-2bb0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm-iE8-ASZhyOjFbGzpSyf7PovVL063Pc',
    appId: '1:142912054370:ios:6a1dc5a3bf7c9ab6d75d3b',
    messagingSenderId: '142912054370',
    projectId: 'tickit-2bb0e',
    storageBucket: 'tickit-2bb0e.firebasestorage.app',
    iosBundleId: 'com.example.flutterMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm-iE8-ASZhyOjFbGzpSyf7PovVL063Pc',
    appId: '1:142912054370:ios:6a1dc5a3bf7c9ab6d75d3b',
    messagingSenderId: '142912054370',
    projectId: 'tickit-2bb0e',
    storageBucket: 'tickit-2bb0e.firebasestorage.app',
    iosBundleId: 'com.example.flutterMain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJVha9vajLAvHf9fiO23vYlfSyCVYugV4',
    appId: '1:142912054370:web:8636fb81f7617af8d75d3b',
    messagingSenderId: '142912054370',
    projectId: 'tickit-2bb0e',
    authDomain: 'tickit-2bb0e.firebaseapp.com',
    storageBucket: 'tickit-2bb0e.firebasestorage.app',
    measurementId: 'G-RT23755ZQR',
  );

}